sonar.projectKey=lyrx
sonar.projectName=lyrx
sonar.projectVersion=1.0
sonar.sources=main.py,src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.coverage.exclusions=tests/**,validation/**,scripts/**
sonar.exclusions=**/.venv/**,**/__pycache__/**,data/**,models/**,NLPMusic.ipynb
